{
    "openapi": "3.0.2",
    "info": {
        "title": "Telemetry Orchestrator API",
        "version": "1.0.0"
    },
    "paths": {
        "/metric/atica/": {
            "get": {
                "tags": [
                    "Prometheus Metrics"
                ],
                "summary": "Get Metrics",
                "operationId": "get_metrics_metric_atica__get",
                "responses": {
                    "200": {
                        "description": "Metrics retrieved",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GetMetricsResponseModel"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Prometheus Metrics"
                ],
                "summary": "Add Metric Data",
                "operationId": "add_metric_data_metric_atica__post",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/MetricModel"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Metric added into the database",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AddMetricResponseModel"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/metric/atica/{id}": {
            "get": {
                "tags": [
                    "Prometheus Metrics"
                ],
                "summary": "Get Metric Data",
                "operationId": "get_metric_data_metric_atica__id__get",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id"
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Metric data retrieved",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GetMetricResponseModel"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Prometheus Metrics"
                ],
                "summary": "Update Metric Data",
                "operationId": "update_metric_data_metric_atica__id__put",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "string"
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateMetricModel"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Metric data updated",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UpdateMetricResponseModel"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Prometheus Metrics"
                ],
                "summary": "Delete Metric Data",
                "operationId": "delete_metric_data_metric_atica__id__delete",
                "parameters": [
                    {
                        "required": true,
                        "schema": {
                            "title": "Id",
                            "type": "string"
                        },
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Metric deleted from the database",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/DeleteMetricResponseModel"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Root"
                ],
                "summary": "Read Root",
                "operationId": "read_root__get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "AddMetricResponseModel": {
                "title": "AddMetricResponseModel",
                "required": [
                    "data",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "title": "Data",
                        "type": "object"
                    },
                    "code": {
                        "title": "Code",
                        "type": "integer",
                        "default": 200
                    },
                    "message": {
                        "title": "Message",
                        "type": "string"
                    }
                },
                "example": {
                    "data": {
                        "id": "62aad459fb672f7a0a80e0cf",
                        "metricname": "node_network_transmit_packets_total",
                        "labels": {
                            "job": "node"
                        },
                        "interval": 10000,
                        "description": "Packets transmitted through network interfaces."
                    },
                    "code": 200,
                    "message": "Metric added successfully."
                }
            },
            "DeleteMetricResponseModel": {
                "title": "DeleteMetricResponseModel",
                "required": [
                    "data",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "title": "Data",
                        "type": "string"
                    },
                    "code": {
                        "title": "Code",
                        "type": "integer",
                        "default": 200
                    },
                    "message": {
                        "title": "Message",
                        "type": "string"
                    }
                },
                "example": {
                    "data": "Metric with ID 62aad459fb672f7a0a80e0cf removed.",
                    "code": 200,
                    "message": "Metric deleted successfully."
                }
            },
            "GetMetricResponseModel": {
                "title": "GetMetricResponseModel",
                "required": [
                    "data",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "title": "Data",
                        "type": "object"
                    },
                    "code": {
                        "title": "Code",
                        "type": "integer",
                        "default": 200
                    },
                    "message": {
                        "title": "Message",
                        "type": "string"
                    }
                },
                "example": {
                    "data": {
                        "id": "62aad459fb672f7a0a80e0cf",
                        "metricname": "node_network_transmit_packets_total",
                        "labels": {
                            "instance": "node-exporter:9100",
                            "job": "node"
                        },
                        "interval": 5000,
                        "description": "Packets transmitted through network interfaces."
                    },
                    "code": 200,
                    "message": "Metric data retrieved successfully."
                }
            },
            "GetMetricsResponseModel": {
                "title": "GetMetricsResponseModel",
                "required": [
                    "data",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "title": "Data",
                        "type": "array",
                        "items": {
                            "type": "object"
                        }
                    },
                    "code": {
                        "title": "Code",
                        "type": "integer",
                        "default": 200
                    },
                    "message": {
                        "title": "Message",
                        "type": "string"
                    }
                },
                "example": {
                    "data": [
                        {
                            "id": "62aad459fb672f7a0a80e0cf",
                            "metricname": "up",
                            "labels": {
                                "instance": "node-exporter:9100",
                                "job": "node"
                            },
                            "interval": 10000,
                            "description": "The node-exporter instance is up."
                        },
                        {
                            "id": "62aad9fa0ecf10140cd50534",
                            "metricname": "node_network_transmit_packets_total",
                            "labels": {
                                "instance": "node-exporter:9100",
                                "job": "node"
                            },
                            "interval": 5000,
                            "description": "Packets transmitted through network interfaces."
                        }
                    ],
                    "code": 200,
                    "message": "Metrics data retrieved successfully."
                }
            },
            "HTTPValidationError": {
                "title": "HTTPValidationError",
                "type": "object",
                "properties": {
                    "detail": {
                        "title": "Detail",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ValidationError"
                        }
                    }
                }
            },
            "MetricModel": {
                "title": "MetricModel",
                "required": [
                    "metricname",
                    "labels",
                    "interval",
                    "description"
                ],
                "type": "object",
                "properties": {
                    "metricname": {
                        "title": "Metricname",
                        "type": "string"
                    },
                    "labels": {
                        "title": "Labels",
                        "type": "object"
                    },
                    "interval": {
                        "title": "Interval",
                        "type": "integer"
                    },
                    "description": {
                        "title": "Description",
                        "type": "string"
                    }
                },
                "example": {
                    "metricname": "node_network_transmit_packets_total",
                    "labels": {
                        "job": "node"
                    },
                    "interval": 10000,
                    "description": "Packets transmitted through network interfaces."
                }
            },
            "UpdateMetricModel": {
                "title": "UpdateMetricModel",
                "type": "object",
                "properties": {
                    "labels": {
                        "title": "Labels",
                        "type": "object"
                    },
                    "interval": {
                        "title": "Interval",
                        "type": "integer"
                    },
                    "description": {
                        "title": "Description",
                        "type": "string"
                    }
                },
                "example": {
                    "labels": {
                        "device": "eth0",
                        "instance": "node-exporter:9100",
                        "job": "node"
                    },
                    "interval": 5000
                }
            },
            "UpdateMetricResponseModel": {
                "title": "UpdateMetricResponseModel",
                "required": [
                    "data",
                    "message"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "title": "Data",
                        "type": "string"
                    },
                    "code": {
                        "title": "Code",
                        "type": "integer",
                        "default": 200
                    },
                    "message": {
                        "title": "Message",
                        "type": "string"
                    }
                },
                "example": {
                    "data": "Metric with ID 62aad459fb672f7a0a80e0cf updated.",
                    "code": 200,
                    "message": "Metric data updated successfully."
                }
            },
            "ValidationError": {
                "title": "ValidationError",
                "required": [
                    "loc",
                    "msg",
                    "type"
                ],
                "type": "object",
                "properties": {
                    "loc": {
                        "title": "Location",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "msg": {
                        "title": "Message",
                        "type": "string"
                    },
                    "type": {
                        "title": "Error Type",
                        "type": "string"
                    }
                }
            }
        }
    }
}